name: Cypress Tests
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: cypress/included
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run Cypress tests
      run: cypress run
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: cypress/screenshots/
        path: cypress/screenshots/
        retention-days: 5